//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ICC.wsIcc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsSincronizacionSoap", Namespace="http://tempuri.org/")]
    public partial class WsSincronizacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FncObtenerDatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubGuardarInformacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubGuardarInformacionYoReportoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsSincronizacion() {
            this.Url = "http://138.128.150.200/ICC/WsSincronizacion.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FncObtenerDatosCompletedEventHandler FncObtenerDatosCompleted;
        
        /// <remarks/>
        public event SubGuardarInformacionCompletedEventHandler SubGuardarInformacionCompleted;
        
        /// <remarks/>
        public event SubGuardarInformacionYoReportoCompletedEventHandler SubGuardarInformacionYoReportoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FncObtenerDatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FncObtenerDatos() {
            object[] results = this.Invoke("FncObtenerDatos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FncObtenerDatosAsync() {
            this.FncObtenerDatosAsync(null);
        }
        
        /// <remarks/>
        public void FncObtenerDatosAsync(object userState) {
            if ((this.FncObtenerDatosOperationCompleted == null)) {
                this.FncObtenerDatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFncObtenerDatosOperationCompleted);
            }
            this.InvokeAsync("FncObtenerDatos", new object[0], this.FncObtenerDatosOperationCompleted, userState);
        }
        
        private void OnFncObtenerDatosOperationCompleted(object arg) {
            if ((this.FncObtenerDatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FncObtenerDatosCompleted(this, new FncObtenerDatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubGuardarInformacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SubGuardarInformacion(string lJsonTransaccion) {
            object[] results = this.Invoke("SubGuardarInformacion", new object[] {
                        lJsonTransaccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubGuardarInformacionAsync(string lJsonTransaccion) {
            this.SubGuardarInformacionAsync(lJsonTransaccion, null);
        }
        
        /// <remarks/>
        public void SubGuardarInformacionAsync(string lJsonTransaccion, object userState) {
            if ((this.SubGuardarInformacionOperationCompleted == null)) {
                this.SubGuardarInformacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubGuardarInformacionOperationCompleted);
            }
            this.InvokeAsync("SubGuardarInformacion", new object[] {
                        lJsonTransaccion}, this.SubGuardarInformacionOperationCompleted, userState);
        }
        
        private void OnSubGuardarInformacionOperationCompleted(object arg) {
            if ((this.SubGuardarInformacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubGuardarInformacionCompleted(this, new SubGuardarInformacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubGuardarInformacionYoReporto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SubGuardarInformacionYoReporto(string lJsonTransaccion) {
            object[] results = this.Invoke("SubGuardarInformacionYoReporto", new object[] {
                        lJsonTransaccion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubGuardarInformacionYoReportoAsync(string lJsonTransaccion) {
            this.SubGuardarInformacionYoReportoAsync(lJsonTransaccion, null);
        }
        
        /// <remarks/>
        public void SubGuardarInformacionYoReportoAsync(string lJsonTransaccion, object userState) {
            if ((this.SubGuardarInformacionYoReportoOperationCompleted == null)) {
                this.SubGuardarInformacionYoReportoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubGuardarInformacionYoReportoOperationCompleted);
            }
            this.InvokeAsync("SubGuardarInformacionYoReporto", new object[] {
                        lJsonTransaccion}, this.SubGuardarInformacionYoReportoOperationCompleted, userState);
        }
        
        private void OnSubGuardarInformacionYoReportoOperationCompleted(object arg) {
            if ((this.SubGuardarInformacionYoReportoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubGuardarInformacionYoReportoCompleted(this, new SubGuardarInformacionYoReportoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void FncObtenerDatosCompletedEventHandler(object sender, FncObtenerDatosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FncObtenerDatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FncObtenerDatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SubGuardarInformacionCompletedEventHandler(object sender, SubGuardarInformacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubGuardarInformacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubGuardarInformacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void SubGuardarInformacionYoReportoCompletedEventHandler(object sender, SubGuardarInformacionYoReportoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubGuardarInformacionYoReportoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubGuardarInformacionYoReportoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591